### ISSUE TITLE
includes/StringUtils.php moved to includes/utils/StringUtils.php

### ISSUE THREAD

**Issue by dschwen** [tszming/mediawiki-zhconverter#1]
In current Mediawiki versions `StringUtils.php` resides in `includes/utils`.

**Comment by dschwen** [comment]
@tszming I suggest you merge teh changes from soarqin/mediawiki-zhconverter instead

**Comment by tszming** [comment]
@dschwen I am happy to merge if @soarqin send me a PR, but honestly I havn't use this project for long time, and if soarqin's fork serve your purpose, why not just use his (better) version :)
